### ISSUE TITLE
Unable to Create New Events

### ISSUE THREAD

**Issue by ianericksen** [vilisseranen/castellers#44]
I was able to create two sets of events, but then when I wanted to edit the end time of an event of the second set, I got an error message. I deleted all the new events, tried to create a new set from March 5th to April 16th, still got a message: Un problème est survenu. Veuillez vérifier les informations fournies.

**Comment by ianericksen** [comment]
I found how to work around.  It seems to fail to edit event because the data is incomplete. If I make sure "pratique" or "présentation" is checked, then I can save.  The current set of event was created without specifying "pratique" or "présentation".

**Comment by ianericksen** [comment]
The "pratique" or "présentation" check list is not properly set when we view an event. It's always empty (no option is checked), even when we checked an option in a previous edit.

**Comment by vilisseranen** [comment]
fixed in #46
